language: php
sudo: false

addons:
  sonarcloud:
    organization: "eromser-github"

git:
  depth: false

script:
#  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
